
/**
 * Save local settings to local storage.
 */
function saveSettings() {
    const serverurl = document.getElementById('serverUrl').value;
    const checkinUrl = document.getElementById('checkinUrl').value;
    const submitUrl = document.getElementById('submitUrl').value;
    const debug = document.getElementById('debug').checked;
    const key = document.getElementById('key').value;

    chrome.storage.sync.set({
        serverurl: serverurl,
        checkinurl: checkinUrl,
        submiturl: submitUrl,
        debug: debug,
        key: key
    }, function () {
        // Update status to let user know options were saved.
        var status = document.getElementById('status');
        status.textContent = 'Options saved.';
        setTimeout(function () {
            status.textContent = '';
        }, 750);
    });
}


/**
 * Update the form to reflect the settings that have been loaded.
 * 
 * Managed settings are reflected by having their controls disabled.
 * 
 * @param {Array} settings Array of managed settings, local settings
 */
function updateFormState(settings) {
    let managedSettings = settings[0];
    let localSettings = settings[1];

    let serverUrlInput = document.getElementById('serverUrl');
    if (managedSettings.serverurl) {
        serverUrlInput.value = managedSettings.serverurl;
        serverUrlInput.disabled = true;
    } else {
        serverUrlInput.value = localSettings.serverurl;
        serverUrlInput.disabled = false;
    }

    let checkinUrlInput = document.getElementById('checkinUrl');
    if (managedSettings.checkinurl) {
        checkinUrlInput.value = managedSettings.checkinurl;
        checkinUrlInput.disabled = true;
    } else {
        checkinUrlInput.value = localSettings.checkinurl;
        checkinUrlInput.disabled = false;
    }   

    let submitUrlInput = document.getElementById('submitUrl');
    if (managedSettings.submiturl) {
        submitUrlInput.value = managedSettings.chesubmiturlckinurl;
        submitUrlInput.disabled = true;
    } else {
        submitUrlInput.value = localSettings.submiturl;
        submitUrlInput.disabled = false;
    }

    document.getElementById('debug').checked = managedSettings.debug !== undefined ? managedSettings.debug : localSettings.debug;
    document.getElementById('key').value = managedSettings.key || localSettings.key;
}

/**
 * Update check-in and submit urls based on the value entered in the server url field, if it changed.
 * 
 * @param {Event} e Event generated by changing the server url.
 */
function updateUrlsFromServerUrl(e) {
    let serverUrl = e.currentTarget.value;
    document.getElementById('checkinUrl').value = serverUrl + "/checkin";
    document.getElementById('submitUrl').value = serverUrl + "/inventory/submit";
}

document.getElementById('serverUrl').addEventListener('change', updateUrlsFromServerUrl);


document.addEventListener('DOMContentLoaded', function (e) {
    Promise.all([
        getManagedSettings(),
        getLocalSettings(),
    ]).then(updateFormState).catch(function (err) {
        console.log(err);
    })
});

document.getElementById('settings-form').addEventListener('submit', function (e) {
    e.preventDefault();
    e.stopPropagation();
    console.log('tried to submit');
});
document.getElementById('save').addEventListener('click', saveSettings);
